apiVersion: v1
kind: Template
labels:
  template: dev-create-buildconfig from gogs repository
message: This Template create the builconfig to build project from gogs repository in dev environment
metadata:
  annotations:
    description: This it deploy springboot application in in dev environment
    iconClass: icon-jboss
    tags: dev, recreate-strategy
  name: dev-recreate-strategy
parameters:
- displayName: Project name
  value: dev
  name: PROJECT
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
       app: test
    name: test
    namespace: dev

