apiVersion: v1
kind: Template
labels:
  template: ci-manager-repo-initialiser
  group: cicd
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: gogs,ci-manager
  name: ci-manager-repo-initialiser
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ci-manager-repo-initialiser
  spec:
    activeDeadlineSeconds: 400
    completions: 1
    parallelism: 1
    template:
      spec:
        containers:
        - env:
          - name: CICD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
          - /bin/bash
          - -x
          - -c
          - |

            CI_MANAGER_HOSTNAME=$(oc get route ci-manager -o template --template='{{.spec.host}}')

            _RETURN=$(curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' \
            "http://${CI_MANAGER_HOSTNAME}/projects?projectName=polaris3&repoUrl=https%3A%2F%2Fgithub.com%2FatSistemas%2Fpolaris.git")

            sleep 5

            if [ $_RETURN != "200" ] && [ $_RETURN != "302" ] ; then
              echo "ERROR: Failed to initialise CI Manager"
              cat /tmp/curl.log
              exit 255
            fi

          image: openshift/origin:v3.9.0
          name: ci-manager-repo-initialiser-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: OnFailure