apiVersion: v1
kind: Template
labels:
  template: dev-recreate-strategy
message: This Template create all the polaris resources to deploy automatically a springboot jar in dev environment
metadata:
  annotations:
    description: This it deploy springboot application in in dev environment
    iconClass: icon-jboss
    tags: dev, recreate-strategy
  name: dev-recreate-strategy
parameters:
- displayName: Project name
  value: dev
  name: PROJECT
  required: true
- displayName: Application name
  value: polaris
  name: APP
  required: true
- displayName: Application jar
  value: spring-boot.jar
  name: JARNAME
  required: true
- displayName: Java 8 image stream
  value: redhat-openjdk18-openshift
  name: JAVA8_IMAGESTREAM
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${APP}
    name: ${APP}
    namespace: ${PROJECT}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP}-service
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: ${APP}-dc
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
      creationTimestamp: '2018-05-23T11:46:22Z'
      generation: 1
      name: ${JAVA8_IMAGESTREAM}
      namespace: ${PROJECT}
  spec:
   dockerImageRepository: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
   lookupPolicy:
     local: false
   tags:
    - annotations:
        description: OpenJDK S2I images.
        iconClass: icon-jboss
        sampleContextDir: undertow-servlet
        sampleRepo: 'https://github.com/jboss-openshift/openshift-quickstarts'
        supports: 'java:8,xpaas:1.0'
        tags: 'builder,java,xpaas'
        version: '1.0'
      generation: 1
      importPolicy: {}
      name: '1.0'
      referencePolicy:
        type: Source
  status:
   dockerImageRepository: '172.30.1.1:5000/dev/${JAVA8_IMAGESTREAM}'
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP}-dc
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${APP}-dc
    strategy:
      # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: ${APP}-dc
      spec:
        containers:
         - env:
            - name: JAVA_APP_JAR
              value: ${JARNAME}
           image: ${PROJECT}/${APP}:latest
           name: ${APP}
           ports:
             - containerPort: 8080
               protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}
        from:
          kind: ImageStreamTag
          name: '${APP}:latest'
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP}-r
  spec:
    to:
      kind: Service
      name: ${APP}-service