apiVersion: v1
kind: Template
labels:
  template: image-stream-openshift-openjdk8
message: This Template create all image stream required for the project
metadata:
  annotations:
    description: Deploys openjdk8 image streams
    iconClass: icon-jboss
    tags: image stream,openjdk8
  name: polaris-DEV
parameters:
- displayName: Project name
  value: dev
  name: PROJECT
  required: true
- displayName: Application name
  value: polaris
  name: APP
  required: true
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
      app: ${APP}
    name: ${APP}
    namespace: ${PROJECT}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP}-service
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: ${APP}-dc
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
      creationTimestamp: '2018-05-23T11:46:22Z'
      generation: 1
      name: redhat-openjdk18-openshift
      namespace: ${PROJECT}
  spec:
   dockerImageRepository: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
   lookupPolicy:
     local: false
   tags:
    - annotations:
        description: OpenJDK S2I images.
        iconClass: icon-jboss
        sampleContextDir: undertow-servlet
        sampleRepo: 'https://github.com/jboss-openshift/openshift-quickstarts'
        supports: 'java:8,xpaas:1.0'
        tags: 'builder,java,xpaas'
        version: '1.0'
      generation: 1
      importPolicy: {}
      name: '1.0'
      referencePolicy:
        type: Source
  status:
   dockerImageRepository: '172.30.1.1:5000/dev/redhat-openjdk18-openshift'