apiVersion: v1
kind: Template
labels:
  template: generate-hook
  group: generate-hook
metadata:
  annotations:
    iconClass: icon-jenkins
    tags: instant-app,jenkins,gogs
  name: generate-hook
message: "Use the following credentials for login:\nGogs Git Server: gogs/gogs"
parameters:
- displayName: DEV project name
  value: dev
  name: DEV_PROJECT
  required: true
- displayName: STAGE project name
  value: stage
  name: STAGE_PROJECT
  required: true
- description: Webhook secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: WEBHOOK_SECRET
  required: true
objects:
# Setup Demo
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: webhook-create-gogs
  spec:
    activeDeadlineSeconds: 400
    completions: 1
    parallelism: 1
    template:
      spec:
        containers:
        - env:
          - name: CICD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
          - /bin/bash
          - -x
          - -c
          - |
            GOGS_ROUTE=$(oc get route gogs -o template --template='{{.spec.host}}')     
            GOGS_USER=gogs
            GOGS_PWD=gogs
            JENKINS_ROUTE=$(oc get route jenkins -o template --template='{{.spec.host}}')
            cat <<EOF > /tmp/data.json
            {
              "type": "gogs",
              "config": {
                "url": "https://${JENKINS_ROUTE}/oapi/v1/namespaces/cicd/buildconfigs/blue-green-pipeline/webhooks/${WEBHOOK_SECRET}/generic",
                "content_type": "json"
              },
              "events": [
                "push"
              ],
              "active": true
            }
            EOF
            _RETURN=$(curl -o /tmp/curl.log -sL -w "%{http_code}" -H "Content-Type: application/json" \
            -u $GOGS_USER:$GOGS_PWD -X POST http://$GOGS_ROUTE/api/v1/repos/gogs/polaris/hooks -d @/tmp/data.json)
            if [ $_RETURN != "201" ] ; then
              echo "ERROR: Failed to set webhook"
              cat /tmp/curl.log
              exit 255
            fi
          image: openshift/origin:v3.9.0
          name: webhook-create-gogs-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Never
