#!/usr/bin/env bash

./demo-cicd-create-projects && \
./demo-cicd-admin-setup && \
./demo-cicd-deploy-stack && \
./demo-cicd-deploy-ci-manager && \
./demo-cicd-deployment-strategies-setup && \
sleep 60
./demo-cicd-ci-manager-initialiser && \
./demo-cicd-start-pipeline