#!/usr/bin/env bash

[[ -z "$OPENSHIFT_URL" ]] && { echo "OpenShift URL not provided, exiting ..." ; exit 1; }

export USERNAME=${USERNAME:="system"}
export PASSWD=${PASSWD:="admin"}

oc login -u $USERNAME -p $PASSWD $OPENSHIFT_URL

# Import image centos7-springboot to build s2i
oc import-image jantonioporras/centos7-springboot:latest --confirm -n openshift

# Make sure latest Jenkins image is installed
oc import-image jenkins:v3.7 --from="registry.access.redhat.com/openshift3/jenkins-2-rhel7" --confirm -n openshift
oc tag jenkins:v3.7 jenkins:latest -n openshift

# Grant Jenkins Access to Projects
echo "Adding roles to admin user ..."
oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n dev
oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n stage
oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n pro

# Manage policy on the cluster
# oc adm policy add-role-to-user admin developer -n dev
#oc adm policy add-role-to-user admin developer -n stage
#oc adm policy add-role-to-user admin developer -n pro
#oc adm policy add-role-to-user admin developer -n cicd

# Update the annotations on namespace resources
#oc annotate --overwrite namespace dev demo=openshift-cd
#oc annotate --overwrite namespace stage demo=openshift-cd
#oc annotate --overwrite namespace pro demo=openshift-cd
#oc annotate --overwrite namespace cicd  demo=openshift-cd

