#!/usr/bin/env bash

[[ -z "$OPENSHIFT_URL" ]] && { echo "OpenShift URL not provided, exiting ..." ; exit 1; }

export USR=${USR:="developer"}
export PASSWD=${PASSWD:="any"}

echo "${USR}"
echo "${PASSWD}"

oc login -u $USR -p $PASSWD $OPENSHIFT_URL

# Create Projects
echo "Creating DEV namespace ..."
oc new-project dev --display-name="Dev Environment" && \
echo "Creating STAGE namespace ..."
oc new-project stage --display-name="Stage environment" && \
echo "Creating PRO namespace ..."
oc new-project pro --display-name="Pro environment" && \
echo "Creating CI/CD namespace ..."
oc new-project cicd --display-name="CI/CD Management"